### PR TITLE
Adding warning label for proposal setup panel for LoKI only

### PR DESCRIPTION
**Pull request by kmurica**
Changes in LoKI ONLY for proposal setup warning label.

### CODE REVIEW

**Comment by umithardal** [comment]
Could you please add me as a reviewer in all PRs if it is related to LoKI. Thanks.

**Comment by kmurica** [comment]
@umithardal sure! this is a breakout of the other branch. I broke out the LoKI parts. As some changes on the Gerrit side has made it necessary to rewrite the code for nicos_ess I have breaken this out to merge asap. The other one I will continue to work on once I have communicated with Matt after his vacation.

**Comment by ebadkamil** [comment]
It looks good to me and also label doesn't jump around anymore.

**Comment by kmurica** [comment]
@umithardal I fixed the bug now with the popups and cleared the proposal number when disconnected.

**Review by umithardal — APPROVED** [review]

**Pull request merged**
