### PR TITLE
ECDC-2684_motor_alarm_log_spam_fix

### PR DESCRIPTION
**Pull request by kmurica**
Fixing issue with spamming of the log when there is an alarm and doStatus is called.

### CODE REVIEW

**Comment by kmurica** [comment]
Ready for review once Matt's caproto fix is merged from  Gerrit.

**Comment by mattclarke** [comment]
I am just preparing a gerrit patch for the monitor motor, so I propose I incorporate these changes there.

**Comment by mattclarke** [comment]
Hopefully, I've ported them correctly to https://forge.frm2.tum.de/review/c/frm2/nicos/nicos/+/27034
I've also added "get_alarm_status" to EpicsDevice which simplifies things a bit, so I have modified the code to use that.

**Comment by kmurica** [comment]
merged from gerrit

**Pull request closed without merging**
