### PR TITLE
Trying to get copy and paste shortcuts to work

### PR DESCRIPTION
**Pull request by mattclarke**
Copy = ctrl/cmd+c
Cut = ctrl/cmd+x
Paste = ctrl/cmd+v
Delete rows = ctrl/cmd+backspace

Also added context menu (i.e. right-click menu) and 'Table' menu in the main menu.
For some reason the 'Edit' menu doesn't show up.

### CODE REVIEW

**Comment by mattclarke** [comment]
Linux report from Ebad:
 - Edit menu does appear
 - Short-cuts still don't work

Time to fire up a VM!

**Comment by mattclarke** [comment]
Okay, this works on my Centos VM, so @ebadkamil please give it a go.
I have basically thrown everything at this, so if it works we can remove some changes and see if still works and so on.
I think the changes to the context for the main NICOS screens is key though.

**Comment by ebadkamil** [comment]
wonderful. It works for me as well. 

One minor thing one can fix is If I click on the table but not on any rows and just click paste, it throws error. Checking for empty indices and return will probably do the job. 

```bash
Traceback (most recent call last):
  File "/home/ebadkamil/nicos_github_fork/nicos_ess/loki/gui/loki_scriptbuilder.py", line 108, in on_actionPaste_triggered
    self._handle_table_paste()
  File "/home/ebadkamil/nicos_github_fork/nicos_ess/loki/gui/loki_scriptbuilder.py", line 261, in _handle_table_paste
    top_left = indices[0]
IndexError: list index out of range

```

**Comment by mattclarke** [comment]
Good spot - thanks!

**Comment by umithardal** [comment]
Works for me as well. I have tried setting context before, and it did not work. I believe addition of the widget to UI files made this work? Is that it? Thanks for the code. A dict switch can remove repetitions (not critical but it would make this commands immutable as well.)

**Comment by umithardal** [comment]
Closes #81

**Comment by ebadkamil** [comment]
Works as expected. LGTM

**Pull request merged**
