### PR TITLE
Clear gui directory up

### PR DESCRIPTION
**Pull request by umithardal**
This PR makes small changes in `nicos_ess/gui`:

- Move ui files in `/panels` to `/panels/ui_files`
- Delete commented out code lines in `gui/statusbar.py`

A question: There is a file in `/panels` called `console.py` which calls out a ui file that does not exists. That call overwrites the main one, as well. Now, do we have plans to use this file? If so we need to create or copy over the corresponding ui file. Else, we need to delete this file as it is error prone.

### CODE REVIEW

**Comment by umithardal** [comment]
I made these changes against master, hope that is fine.

**Comment by mattclarke** [comment]
These changes look good. 

Rather than merge them here it would be better to put them directly into Gerrit.

I think you are right about the console, but check with Michele

**Comment by umithardal** [comment]
Sure, after making a PR to Gerrit I will close this one.

**Comment by umithardal** [comment]
A PR has been made to Gerrit.

**Pull request closed without merging**
