### PR TITLE
ECDC-2264 color cmd line when busy

### PR DESCRIPTION
**Pull request by kmurica**
Ongoing work to use purely stylesheets to change graphic properties of widgets.

### CODE REVIEW

**Comment by kmurica** [comment]
This is under review in Gerrit.

**Comment by mattclarke** [comment]
https://forge.frm2.tum.de/review/c/frm2/nicos/nicos/+/25021

**Comment by mattclarke** [comment]
This can be closed now the Gerrit version is merged, right?

**Comment by kmurica** [comment]
@mattclarke what happens to the Loki parts which are not merged in Gerrit (.qss file and .ui file if I remember correctly)?

**Comment by kmurica** [comment]
Merged in Gerrit. Creating separate branch for loki specific qss file to merge to main.

**Pull request closed without merging**
