### PR TITLE
Uncheck expert mode when disconnected

### PR DESCRIPTION
**Pull request by umithardal**
This PR fixes expert mode option. The problem was

- Expert mode can be checked even if client is not connected to a server.
- Expert mode stays checked after the disconnection (this I realised while working on the problem).

The fix required changing some code in the parent. During this fix I realised that (took some time) `setChecked(bool)` of pyqt5 makes tailing calls to the function under consideration. This created some problems. I managed the find a work around and believe that this is bug in the implementation. 

In the ESS child, I made `expert mode` disabled but visible if there is no connection. I believe that this is a more elegant way than raising a box saying that we are not connected.

After we decide the faith of this implementation, I will make the same PR to Gerrit and close this one.

### CODE REVIEW

**Comment by mattclarke** [comment]
I like the idea of disabling the item when disconnected a lot. 
Though as it goes into core, I think we should discuss with the others what we should expect to happen to expert mode when the client disconnects.
I'll bring it up in the meeting this afternoon.

Looking at the original code, I think the reason for the error messages is in core devices.py file, namely:
```
    def setExpertMode(self, expert):
        self._show_lowlevel = expert
        self.on_client_connected()
```
It tries to call `on_client_connected` even though the client is disconnected. Probably just needs a check to see if the client is connected or not. 
We should fix that in Gerrit in a completely separate PR - do you have time to do that?

**Comment by umithardal** [comment]
Sure I can look at it and see if that fix the tailing calls. I agree, I do want to know what is expected concerning expert mode in general.

**Comment by mattclarke** [comment]
Just to make sure we are on the same page :D
My suggestion above regarding devices.py relates to the code in the current master version of NICOS not this PR.

**Comment by umithardal** [comment]
Now I am confused. You say your suggestion would not fix the problem?

**Comment by mattclarke** [comment]
Don't worry, I'll sort it out.

**Comment by mattclarke** [comment]
Easier to explain in code
:D

**Comment by mattclarke** [comment]
This has been replaced by a PR in Gerrit

**Pull request closed without merging**
