### PR TITLE
ECDC-2334: Dream instrument

### PR DESCRIPTION
**Pull request by ebadkamil**
The demo for this instrument requires simulated motor IOC, kafka broker, just-bin-it and an instance of Filewriter running with appropriate configuration.

### CODE REVIEW

**Comment by mattclarke** [comment]
Looking good. 
It would be nice to be able to share the qss file from the nicos_ess directory as they should always be the same.
Can you see if that is possible pls?
It might not be, but worth trying...

**Comment by ebadkamil** [comment]
@mattclarke just browsing through the code 
 https://github.com/ess-dmsc/nicos/blob/2dcd33e1446839e92b1fae79fae9edec9814ce7b/nicos/clients/gui/main.py#L127

it seems `main.py` code looks for files in the instrument path that ends with `.qss` and if found adds that as an attribute to `gui_conf` which is later used to set the stylesheet in MainWindow.  So as of now looks like we have to carry .qss files around. May be there is a better way. I will dig deeper.

**Comment by mattclarke** [comment]
Thanks for looking, don't bother digging any further.

**Comment by mattclarke** [comment]
Feel free to fire this into Gerrit when you are happy

**Pull request closed without merging**
