### PR TITLE
Remove tick symbol next to Disconnect in dropdown menu

### PR DESCRIPTION
**Pull request by umithardal**
This PR removes the unnecessary tick symbol next to `Disconnect` in the dropdown menu of the main ui that appears after connection is established. Some unused arguments in the functions has also been removed.

### CODE REVIEW

**Comment by mattclarke** [comment]
This is broken - disconnect now no longer disconnects (see what happens when `cancel` is clicked on the connection dialog after disconnecting).
Also, compare it to the original behaviour.

It would be better if we made the changes to the nicos_ess version of mainwindow rather than change the "core" NICOS mainwindow.

My suspicion is that this ticket is harder than I initially thought - sorry 🙏

**Comment by umithardal** [comment]
That is fine, no worries. But the code that changes this behaviour does not exists in NICOS_ess, unless you want me to write one that inherits and overwrites.

**Comment by mattclarke** [comment]
Bingo! That sounds like a way forward 👍

**Comment by umithardal** [comment]
@mattclarke The new changes should do it. Please check if everything works properly. I will update the card accordingly.

Now, what I have done is to make `QAction` button not checkable in the UI (using designer). Then, I removed the code lines that calls related functions. And finally change the logic flow at line `227` so that everything is properly updated.

I made some code corrections here and there as well. One question though; this code uses or tries to use `sshtunnel` library which is not in our requirements? May be we should add it?

**Comment by umithardal** [comment]
Ok `sshtunnel` is in the optional requirements, but I do not think it is optional :)

**Review by mattclarke — APPROVED** [review]
Looks good and works well.

I don't think we will need the SSH stuff, so perhaps we should just remove it all?
If it does turn out that we do need it then we can always re-add it later.

**Pull request merged**
