### PR TITLE
Add dependency for Yuos Query

### PR DESCRIPTION
**Pull request by ebadkamil**

### CODE REVIEW

**Comment by mattclarke** [comment]
Weird, it should have come across from Gerrit.

**Comment by mattclarke** [comment]
Well spotted!

**Comment by ebadkamil** [comment]
will you create a PR on gerrit? Then we can close this one once it is merged there.

**Comment by jkrueger1** [comment]
> will you create a PR on gerrit? Then we can close this one once it is merged there.

BTW, don't you have an account at Gerrit?

**Comment by ebadkamil** [comment]
@jkrueger1 oh yes I do have. I was just wondering if Matt wants to do it.

**Comment by mattclarke** [comment]
@ebadkamil: It is already in gerrit that was why I was surprised it hadn't come across.

**Comment by ebadkamil** [comment]
@mattclarke strange.

**Comment by mattclarke** [comment]
We should make sure the one in gerrit is the definitive one, so we should copy any differences that have crept into this one over to there.
I'll let you do that ;)

**Comment by jkrueger1** [comment]
Did you sync this repo against the official? May be it was forgotten or a merge was wrong made.

**Comment by mattclarke** [comment]
Yeah, we sync it once a week. I suspect a merge conflict was resolved incorrectly

**Pull request merged**
