### PR TITLE
Add FW Contol Library to requirements

### PR DESCRIPTION
**Pull request by umithardal**
This add the File Writer Contol Library to Nicos ESS requirements.

### CODE REVIEW

**Comment by mattclarke** [comment]
@umithardal Can you pin the version, please?
As the library is still in development the API will change so we probably should prepare for that.

**Comment by umithardal** [comment]
@mattclarke should this be merged?

**Comment by mattclarke** [comment]
It will come through Gerrit eventually, right?
If so, perhaps we just close it?

**Comment by mattclarke** [comment]
Up to you though, merge it if you want

**Comment by umithardal** [comment]
This is already in Gerrit.

**Pull request closed without merging**
