### PR TITLE
LoKI: Enable shortcuts in Prototype Table

### PR DESCRIPTION
**Pull request by umithardal**
This PR introduces keyboard shortcuts to manipulate cells in `Prototype` tab of the LoKI GUI. As many of the keyboard shortcuts are reserved or used by either QT or Nicos Core, we define:

- `Copy`: _Ctrl+Alt+C_
- `Paste`: _Ctrl+Alt+V_
- `Cut`: _Ctrl+Alt+X_
- `Delete`: _Ctrl+Alt+Del_ or _Ctrl+Alt+Backspace_

By default, in Windows `Ctrl` refers to control key while in Mac it is the command key. The code has not been tested against Linux (or Windows if relevant), hoping @ebadkamil can handle Linux part (it should be control key in Linux but who knows).

### CODE REVIEW

**Comment by mattclarke** [comment]
Thanks for trying, but, sorry, but this won't be suitable from a usability view.

If the shortcut keys are different from every other piece of software in the world (and other parts of NICOS) then it would be better not to have them at all. It will just cause more pain.

We'll need to think of an alternative strategy.

**Comment by umithardal** [comment]
Ok, but I do not see any harm these being in. Also, it is very common to create custom shortcuts for a given application. And I do not see why they are not usable? I would much more prefer these specific set, other than system wise ones as you can mistakenly paste something that is in the OS clipboard if it were `Ctrl+V` only. 

In any case, please do not close this PR until I am sure there is no way.

**Comment by umithardal** [comment]
As an example Nicos use `Ctrl+Shift+C` to cut the connection. So, in Nicos we have custom ones already.

**Comment by mattclarke** [comment]
That is a custom shortcut for a custom behaviour, which is fine.

Copy/cut/paste shortcuts are universal, even my mum knows what they are ;)

There surely must be another way and with your eye for detail I think you are the best chance we have.

**Comment by mattclarke** [comment]
I think I may have a solution, need to do a bit of digging first though...

**Pull request closed without merging**
